# Berisi profil pengaturan untuk koneksi ke database MySQL
port: 8001
database:
  driver: "mysql"
  host: "localhost"
  port: "3306"
  user: "root"
  password: "admin123"
  db_name: "mcr_auth_service"
  config: "charset=utf8&parseTime=True&loc=Local"